src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/json/JsonBinary.java
turns out I failed to actually run the test I wrote under a version of mysql that exposes the bug
=> fix bugs exposed by adding array test

src/main/java/com/github/shyiko/mysql/binlog/event/LRUCache.java, src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/EventDeserializer.java
see https://github.com/zendesk/maxwell/issues/1468 for the full story.
I'm not even sure how big this LRUCache really needs to be, given that
we unconditionally put stuff in it before every transaction.  I think
the size might need to be 1?  Unclear.
=> prevent TableMapEventData hash from growing unbounded.

src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java, src/test/java/com/github/shyiko/mysql/binlog/BinaryLogClientIntegrationTest.java
I experience an issue on production for maxwell, where an exception occurred during connection to a database that had experienced many failovers. However the exception was uncaught, and our maxwell container continued to operate in a bad state.
Going through the code here, it looks like only IOExceptions were caught by the code, causing the IllegalStateException thrown when there is already a connection to fall through the cracks. Here we force all exceptions to propagate out, and successfully terminate the application when one occurs.
=> Propagate all exceptions that occur in connectTimeout thread

src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java
It looks like AuthenticationException was a subclass of IOException, which is why most errors were able to be caught originally.
This PR changes the exception handling so that only non-IOExceptions are recast as IOExceptions.
=> fixed auth exception test

README.md
latest version of `com.zendesk:mysql-binlog-connector-java` is here: https://search.maven.org/search?q=g:com.zendesk%20AND%20a:mysql-binlog-connector-java
=> update maven url

src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/AbstractRowsEventDataDeserializer.java, src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/EventDeserializer.java, src/test/java/com/github/shyiko/mysql/binlog/BinaryLogClientIntegrationTest.java, src/test/onetimeserver
I run `mvn checkstyle:check` but so many errors, so I am not sure whether the style is followed now. 
```
...
[ERROR] src/main/java/com/github/shyiko/mysql/binlog/network/SocketFactory.java:[26,5] (javadoc) MissingJavadocMethod: 缺少 Javadoc 。
[ERROR] src/main/java/com/github/shyiko/mysql/binlog/network/SSLMode.java:[19] (sizes) LineLength: 本行字符数 112个，最多：80个。
[ERROR] src/main/java/com/github/shyiko/mysql/binlog/network/SSLMode.java:[26] (sizes) LineLength: 本行字符数 91个，最多：80个。
[ERROR] src/main/java/com/github/shyiko/mysql/binlog/network/SSLMode.java:[36] (sizes) LineLength: 本行字符数 81个，最多：80个。
[ERROR] src/main/java/com/github/shyiko/mysql/binlog/network/SSLMode.java:[40] (sizes) LineLength: 本行字符数 117个，最多：80个。
[ERROR] src/main/java/com/github/shyiko/mysql/binlog/network/SSLMode.java:[41] (sizes) …
```
=> Add option to parse integer as byte array

src/main/java/com/github/shyiko/mysql/binlog/network/protocol/command/AuthenticateSecurityPasswordCommand.java
PLUGIN_AUTH is listed as one of the capabilities and connections to Azure MySQL require the Auth Plugin Name to be specified when that capability is present. If it is not there, Azure MySQL instances respond with "The connection string may not be right. Please visit portal for references.".
See https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::HandshakeResponse and https://github.com/osheroff/mysql-binlog-connector-java/issues/26 for more details about the investigation.
=> Add Auth Plugin Name to for native password auth to fix Azure connections

pom.xml, src/main/java/com/github/shyiko/mysql/binlog/network/HostnameChecker.java, src/main/java/com/github/shyiko/mysql/binlog/network/TLSHostnameVerifier.java, src/test/java/com/github/shyiko/mysql/binlog/BinaryLogClientTest.java
`sun.security.util` went full on don't-use me in Java 11, so I copied the relevant hostname checking out of not-going-to-be-commons ssl.  I can't say it's the most elegant thing I've written in my career but I've tested it and it works. 
@gunnarmorling any objections if I make binlog-connector jdk11+?
=> Replace tls hostname verifier, upgrade to JDK 11

src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/json/JsonBinary.java, src/main/java/com/github/shyiko/mysql/binlog/io/ByteArrayInputStream.java
When the JSON parser was skipping parts of the stream it used default skip implementation. The default one is base on reading the content of the stream to skip to the position which has O(n^2) comeplexity and becomes very slow for large JSON files.
By providing this method we just move the marker in the underlying stream without the need to go through expensive reading.
=> Provide fast skip method implementation

src/main/java/com/github/shyiko/mysql/binlog/io/ByteArrayInputStream.java, src/test/java/com/github/shyiko/mysql/binlog/io/ByteArrayInputStreamTest.java
`com.github.shyiko.mysql.binlog.io.ByteArrayInputStream` doesn’t override the implementation of `public int read(byte b[], int off, int len)` from `java.io.InputStream`. This leads to the fact that a call to `ByteArrayInputStream#read(int length)` falls back to the default implementation which reads bytes one by one via `int read()`. Essentially, we have one call to `read()` for each byte of the binlog.
Adding an optimal implementation of `public int read(byte b[], int off, int len)` to `com.github.shyiko.mysql.binlog.io.ByteArrayInputStream` gives 2x throughput boost according to my tests. This is going to vary depending on the schema but it should give a significant performance improvement in all cases.
=> Optimize read operation on ByteArrayInputStream

pom.xml, src/main/java/com/github/shyiko/mysql/binlog/network/DefaultSSLSocketFactory.java
As of JDK 11.0.11, TLS1.0 and TLS1.1 have been disabled by default. This change sets the default SSLSocketFactory to use TLSv1.2 to be consistent with JDK 11.0.11.
Reference for JDK 11.0.11: https://www.oracle.com/java/technologies/javase/11-0-11-relnotes.html#JDK-8202343
=> Set DefaultSSLSocketFactory to TLSv1.2 in line with JDK 11.0.11: 

src/main/java/com/github/shyiko/mysql/binlog/event/TableMapEventMetadata.java, src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/TableMapEventDataDeserializer.java, src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/TableMapEventMetadataDeserializer.java, src/test/java/com/github/shyiko/mysql/binlog/BinaryLogClientIntegrationTest.java, src/test/java/com/github/shyiko/mysql/binlog/MysqlOnetimeServer.java, src/test/java/com/github/shyiko/mysql/binlog/MysqlOnetimeServerOptions.java
~A first draft for solving #40, completely untested still, though. I cannot get this project's test suite to run with 8.0.23 (see my comment on that on the issue itself), and when testing within Debezium and MySQL 8.0.23 or newer, I fail to ever receive any table map events with that visibility field.~
Fix for #40. Ready for review.
=> #40 Adding support for column visibility as supported by MySQL 8.0.23

src/main/java/com/github/shyiko/mysql/binlog/io/ByteArrayInputStream.java
The additional details should simplify troubleshooting EOF exceptions in the binlog connector (https://github.com/osheroff/mysql-binlog-connector-java/issues/15, https://github.com/osheroff/mysql-binlog-connector-java/issues/50). By knowing the details, one can replicate the binlog to the local development environment and examine it at the position of failure. For instance, one can confirm that the binlog is intact, and the root cause of the issue is somewhere else.
Example error messages:
> Failed to read remaining 28 of 36 bytes from position 1596693181. Block length: 7347. Initial block length: 8133.
or
> Failed to read next byte from position 20131056
=> Add details to the EOF exceptions

src/main/java/com/github/shyiko/mysql/binlog/jmx/BinaryLogClientStatistics.java
I've found the existence of HEARTBEAT events. These events do not contain timestamp in their header, therefore the current way of computing `secondsBehindMaster` does not work:
``` java
(timestampOfLastEvent  - eventHeader.getTimestamp()) / 1000
```
This is the HEARTBEAT event type definition:
> An artificial event generated by the master. It isn't written to the relay logs.
>It is added by the master after the replication connection was idle for x-seconds to update the slave's Seconds_Behind_Master timestamp in the SHOW SLAVE STATUS output.
>It has no payload nor post-header.
So I think it makes sense in the current implementation of `secondsBehindMaster` to compute it as `0` seconds behind master.
=> avoid computing lag for events not having timestamp (HEARTBEAT)

README.md, src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java, src/main/java/com/github/shyiko/mysql/binlog/MariadbBinaryLogClient.java, src/main/java/com/github/shyiko/mysql/binlog/MariadbGtidSet.java, src/main/java/com/github/shyiko/mysql/binlog/event/AnnotateRowsEventData.java, src/main/java/com/github/shyiko/mysql/binlog/event/EventType.java, src/main/java/com/github/shyiko/mysql/binlog/event/MariadbGtidEventData.java, src/main/java/com/github/shyiko/mysql/binlog/event/MariadbGtidListEventData.java, src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/AnnotateRowsEventDataDeserializer.java, src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/EventDeserializer.java, src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/EventHeaderV4Deserializer.java, src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/MariadbGtidEventDataDeserializer.java, src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/MariadbGtidListEventDataDeserializer.java, src/main/java/com/github/shyiko/mysql/binlog/network/protocol/command/DumpBinaryLogCommand.java, src/test/java/com/github/shyiko/mysql/binlog/BinaryLogClientMariadbIntegrationTest.java, src/test/java/com/github/shyiko/mysql/binlog/MariadbBinaryLogClientIntegrationTest.java, src/test/java/com/github/shyiko/mysql/binlog/MariadbGtidSetTest.java, src/test/java/com/github/shyiko/mysql/binlog/event/deserialization/AnnotateRowsEventDataDeserializerTest.java, src/test/java/com/github/shyiko/mysql/binlog/event/deserialization/MariadbGtidEventDataDeserializerTest.java, src/test/java/com/github/shyiko/mysql/binlog/event/deserialization/MariadbGtidListEventDataDeserializerTest.java
1. Change EventType to use eventNumber not ordinal().
`
ANNOTATE_ROWS(160),
MARIADB_GTID(162)
MARIADB_GTID_LIST(163)
`
2. Add MariaDB event data implements, not only types.
3. Now MariaDB can support query(sql) event and GTID events
@osheroff pls check this PR, ths.
=> Adding support Mariadb events, such as GTID and annotate rows event(sql)

src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java, src/test/java/com/github/shyiko/mysql/binlog/BinaryLogClientIntegrationTest.java
I think it's fair to say we understand ANNOTATE_ROWS_EVENT, but none of
the other stuff represented by this variable is true.
=> correct mariadb_slave_capability value

src/main/java/com/github/shyiko/mysql/binlog/MariadbGtidSet.java
Currently, isContainedWithin will return false when the gtid sets are equal, even though equivalence implies that one contains the other and vice versa, per the contract of the method it's overriding:
https://github.com/osheroff/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/GtidSet.java#L122
Right now this breaks logical equivalence for anyone that uses this to determine whether two sets are logically equal
Link https://github.com/osheroff/mysql-binlog-connector-java/issues/91
=> Fix isContainedWithin for MariaDb to correctly return true when ranges are equivalent

src/main/java/com/github/shyiko/mysql/binlog/io/ByteArrayInputStream.java
Allocation profiling shows Integer boxing originating from this class causes a sizable amount of garbage. This is probably mostly caused by "pos" because its values are almost always bigger than 127, thus missing the IntegerCache.
=> Reduce Integer boxing in ByteArrayInputStream

src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/json/JsonStringFormatter.java, src/test/java/com/github/shyiko/mysql/binlog/event/deserialization/json/JsonStringFormatterTest.java
Exposed initial capacity of StringBuilder through the JsonStringFormatter constructor to be able to avoid allocating a lot of new internal buffers in StringBuilder for large Json values. Also removed unnecessary calls to Integer.toString and Long.toString.
=> Exposed initial capacity of StringBuilder through the JsonStringFormatter constructor

src/test/java/com/github/shyiko/mysql/binlog/BinaryLogClientGTIDIntegrationTest.java
Hi @osheroff, I noticed the build broke on circleci because of my new integration test, maybe the execution order was different, the problem was it got more than one XID event (because of other transactions I suppose).
I narrowed the scope of my integration test:
We're only interested in one GTID event to check the for the serverId. Connect to master because we don't want a replica serverId in the first gtid.
=> Fix circleci build, in the integration test suite multiple events could be in the binary log

src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/TableMapEventDataDeserializer.java, src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/TableMapEventMetadataDeserializer.java, src/test/java/com/github/shyiko/mysql/binlog/OptionalMetaDataIntegrationTest.java, src/test/java/com/github/shyiko/mysql/binlog/event/deserialization/TableMapEventMetadataDeserializerTest.java
I was implementing optional_metadata field in table_map_event for [python-mysql-replication](https://github.com/julien-duponchelle/python-mysql-replication).
- Add convertColumnOrder function 
optional metadata type *SIGNEDNESS*  case
The order of indices in the Inputstream corresponds to the order of numeric columns 
So we need to map the index  to all columns index(include non numeric type columns)
SIGNEDNESS bit map now result is  **signedness={0, 2}**,  but we expect result should be **signedness={0, 3},**
Because test3 table column col1 and col4 are unsigned
AS-IS 
- sql  
```
create table test3( col1 int unsigned , col2 int, col3 varchar(30), col4 int unsigned)
insert into test3 values (1,2,3,4)
```
- application log 
```
Event{header=EventHeaderV4{timestamp=1692014933000, …
```
=> fix bug signedness order change to All Column Order

src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java
This allows us (Debezium) to more easily use the MySQL BinlogClient within Debezium to receive events that are serialized more like what is expected with MySQL rather than explicitly using newer formats that are more MariaDB specific.
=> Make mariadb_slave_capability configurable

src/main/java/com/github/shyiko/mysql/binlog/event/GtidEventData.java, src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/GtidEventDataDeserializer.java, src/test/java/com/github/shyiko/mysql/binlog/event/deserialization/MysqlGtidEventDataDeserializerTest.java
Getting actual high resolution millisecond binlog event time values is not supported by the binlog event header as the timestamp field is [represented as 4 bytes](https://github.com/percona/percona-server/blob/8.0/libbinlogevents/src/binlog_event.cpp#L196) and only [supports second resolution](https://github.com/percona/percona-server/blob/8.0/libbinlogevents/include/binlog_event.h#L612-L617). This basically cannot change without breaking binary compatibility and subsequently replication and binlog tooling as the [19 byte header offset](https://github.com/percona/percona-server/blob/8.0/libbinlogevents/include/binlog_event.h#L418) is hardcoded in so many spots.
We're pushing Shopify's CDC stack (this client and Debezium MySQL connector based) for lower latency to drive new business use …
=> Introduce support for MySQL 8 specific metadata on GTID events

src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/GtidEventDataDeserializer.java, src/main/java/com/github/shyiko/mysql/binlog/io/ByteArrayInputStream.java
=> bugfix: read long value when deserializing gtid transaction's length

src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/TableMapEventMetadataDeserializer.java
resolve #134 
without Break we can not go this Block
```
remainingBytes -= fieldLength;
```
So InputStream  goes wrong position.
@Naros @osheroff 
I think we need hotfix?
reproduce this Issue Step
```
CREATE TABLE `enum_test` (
`int_column` int NOT NULL AUTO_INCREMENT,
`smallint_column` int NOT NULL,
`enum_column` enum('a','b','c') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`datetime_column` datetime(6) DEFAULT CURRENT_TIMESTAMP(6),
PRIMARY KEY (`int_column`)
) ENGINE=InnoDB AUTO_INCREMENT=864 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
INSERT INTO `enum_test` (`smallint_column`, `enum_column`, `datetime_column`) 
VALUES 
(10, 'a', '2023-12-01 08:30:00'),
(20, 'b', '2023-12-01 09:45:00'),
(15, 'c', '2023-12-01 10:15:00');
alter table enum_test add column `userType` …
```
=> hot fix optional metadata Extraction
